### PR TITLE
Convert XLF to YAML translations

### PR DESCRIPTION
**Pull request by eSlider**
Translations converting from XLF to human readable/writable YAML format.

### CODE REVIEW

**Comment by astroidex** [comment]
* Benno restructured the yml files and checked them. Please merge

**Comment by werrolf** [comment]
@LazerTiberius we should just merge hotfix/translations back into this branch, it's based on it anyway.

**Comment by LazerTiberius** [comment]
@werrolf Done

**Comment by werrolf** [comment]
@astroidex @eSlider I will keep hotfix/translations open for ongoing fixes. This branch will drop in 3... 2... 1...

**Comment by astroidex** [comment]
sure. Thanks @werrolf  for dropping this branch. We do not need it. All changes are in branch **hotfix/translations**

**Pull request merged**
